name: 功能特性 / Enhancement
description:  "提议新功能，或改善已有功能 / New feature request or enhancement suggestion"
labels: [C-enhancement]
body:
- type: checkboxes
  attributes:
    label: Sophon Service / 智子服务  
    description: |
      Please select the related components.
      请选择涉及模块。
    options:
      - label: venus
        required: false
      - label: sophon-auth
        required: false
      - label: sophon-gateway
        required: false
      - label: sophon-messager
        required: false
      - label: sophon-miner
        required: false
      - label: docs / 文档 
        required: false
- type: textarea
  id: description
  attributes:
    label: Description / 描述
    placeholder: |
      I suggest ...
      是否可以考虑...
  validations:
    required: true
